version: '3.8'

services:
  backend:
    image: adalahub-spring-app:latest
    ports:
      - "8082:8080"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sanaebb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - mysql

  frontend:
    build: ./FrontEnd
    ports:
      - "80:82"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sanaebb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
